const base_url = '';

const getURL = (key, params=[])=> {

  try{
    const urlBank = {
      SIGN_IN: '/api/auth/signin',
      SIGN_UP: '/api/auth/signup',
      TEAM: `/api/team/${params[0]||''}`,
      SELECT_TEAM: `/api/team/chaabi/${params[0]||''}`,
      TEAM_MEMBER: `/api/team/${params[0]||''}/member/${params[1]||''}`,
      ADD_WIDGET: '/api/analytics/addWidget',
      GET_WIDGETS: '/api/analytics/getAnalytics',
      GET_WIDGETS_DATA: '/api/analytics/getAnalyticsOfWidget',
      GET_MEMBERS: '/api/member',
      ASSIGN_REQUEST: `/api/task/${params[0]}/${params[1]}/assign`,
      CHANGE_STATUS: `/api/task/${params[0]}/${params[1]}/status`,
      GET_LOCATIONS: '/api/userLocation/getLocations',
      BOOKINGS: `/api/book-parcel/${params[0]||''}`,
      ASSIGN_BOOKINGS: '/api/book-parcel/assign',
      SEARCH_AWB: `/api/book-parcel/searchAWB/${params[0]}`,
      CHILDREN_TEAMS: '/api/team/children/teams',
      GET_PERMISSIONS: '/api/user/getAllPermissions',
      ALLOCATE_STATIONERY: `/api/allocate-stationery/${params[0]||''}`,
      ADD_MEMBER: `/api/team/${params[0]||''}/addMember`,
      TOGGLE_STATIONERY_STATUS: `/api/allocate-stationery/${params[0]}/status`,
      CHANGE_BULK_STATUS: '/api/book-parcel/changeBulkStatus',
      TEMP_GET_USER: `/api/user/getUserDetails/${params[0]}/${params[1]}`,
      FORGOT_PASSWORD: '/api/auth/forgot-password',
      VERIFY_OTP: '/api/auth/verify-otp',
      TRANSFER_OWNERSHIP: `/api/team/${params[0]}/transfer-ownership`,
      DELIVERY_REPORT: '/api/analytics/delivery-report',
      GET_PARCEL_DETAILS: '/api/book-parcel/getParcelDetails',
      POST_DRS: '/api/drs',
      SEARCH_DRS: `/api/drs/searchDRS/${params[0]}`,
      TRACK_AWB: `/api/public/trackAWB`,
      TRACK_PROOF: `/api/public/trackProof/${params[0]}`,
      ETA_DELIVERY_REPORT: '/api/analytics/eta-delivery-report',
      BOOKING_DATA_CSV: '/api/book-parcel/csv',
      UPLOAD_DRS_IMAGES: `/api/drs/${params[0]}/media`,
      GET_SCANNINGS: '/api/book-parcel/getScanning',
      GET_AWB_SCANNING: '/api/book-parcel/get-scanning',
      SEARCH_BAG: `/api/bagging/searchBag/${params[0]}`,
      POST_BAGGING: '/api/bagging',
      CUSTOMER: `/api/customer/${params[0]||''}`,
      LINKED_CUSTOMERS: '/api/team/linked/customers',
      GET_COLOADERS: '/api/coloaders',
      GET_ORG_COLOADERS: '/api/coloaders/get-all-coloaders',
      GET_COLOADER_DRIVERS: '/api/coloaders/get-drivers',
      GET_COLOADER_VEHICLES: '/api/coloaders/get-vehicles',
      IMPORT_COLOADER: '/api/coloaders/import-coloader',
      CREATE_DRIVER: '/api/coloaders/create-driver',
      CREATE_VEHICLE: '/api/coloaders/create-vehicle',
      CREATE_MOV_ORDER: '/api/movOrder',
      ADD_TO_MOV_ORDER: `/api/movOrder/${params[0]}`,
      DELETE_CONTENT_MOV: `/api/movOrder/${params[0]}/${params[1]}`,
      GET_INCOMING_ORDERS: '/api/movOrder/incoming-orders',
      ACCEPT_MOV_ORDERS: '/api/movOrder/accept-orders',
      GET_RECEIVED_ORDERS: '/api/movOrder/get-received-orders',
      GET_MOVEMENT_ORDER_DETAILS: '/api/movOrder/get-movement-order-details',
      POST_SCAN_IN: `/api/movOrder/scan-in/${params[0]}`,
      STATIONERY: '/api/stationery',
      PRODUCT: '/api/product',
      CHANGE_PRODUCT_STATUS: `/api/product/${params[0]}/change-status`,
      MARK_STATIONERY_SPOILED: `/api/allocate-stationery/${params[0]}/spoiled`,
      CHANGE_STATIONERY_STATUS: `/api/stationery/${params[0]}/change-status`,
      SEARCH_AWB_FOR_DRS: `/api/drs/searchAWB/${params[0]}`,
      GET_GEO_LEVEL_TYPES: '/api/geo/level/type/list',
      LOG_ADDRESSES_BY_PHONE: `/api/address/${params[0]||''}`,
      GET_CREATED_MOVEMENT_ORDER_LIST: '/api/movOrder/created-orders',
      CALCULATE_BOOKING_PRICES: `/api/pricing/group-pricing/calculate`,
      BOOKING_REPORT: `/api/analytics/bookings-report`,
      AGENT_DELIVERY_REPORT: `/api/analytics/agent-delivery-report`,
      ADD_WEBHOOK_USER: '/api/webhook/add-webhook-user',
      GET_WEBHOOK_LIST: '/api/webhook/get-hooks-list',
      GET_BOOKINGS: `/api/book-parcel/bookings/${params[0]||''}`,
      PUT_TOGGLE_WEBHOOK: `/api/webhook/toggle-webhook/${params[0] || ''}`,
      DEL_WEBHOOK: `/api/webhook/${params[0] || ''}`,
      GET_ALL_ORGS: '/api/super/get-all-orgs',
      GET_REQUEST_COUNT_WITH_DATE: `/api/super/${params[0]}/get-bookings-count`,
      POST_EDIT_WEBHOOK: '/api/webhook',
      GET_SCANNING_COUNT_WITH_DATA: `/api/super/${params[0]}/get-scanning-count`,
      VALIDATE_AWB: `/api/book-parcel/awb/${params||''}`,
      SEARCH_LOCATIONS: '/api/geo/fleetyx/master/location/list',
      GROUP_PRICING_SAVE: '/api/pricing/group-pricing/save',
      GROUP_PRICING_LIST: '/api/pricing/group-pricing/list',
      GROUP_PRICING_GROUPED_LIST: '/api/pricing/group-pricing/grouped-list',
      GET_TEAM_ID_LINKED_CUSTOMER: `/api/team/getTeamIdOfLinkedCustomer/${params[0]}`,
      SCAN_IN_SEARCH_BAG: `/api/movOrder/searchBag/${params[0]}`,
      TRANSFER_TEAM: `/api/team/${params[0]}/transferTeam`,
      SEARCH_SCAN_AWB: `/api/book-parcel/searchScanAWB/${params[0]}`,
      SEARCH_SCAN_OUT_AWB: `/api/book-parcel/searchScanOutAWB/${params[0]}`,
      SCAN_IN_AWB: `/api/movOrder/scan-in-awb/${params[0]}`,
      GET_CHILDREN_TEAM_TREE: `/api/team/${params[0]}/getImmediateChildrenTeams`,
      GET_TEAM_BAGS: `/api/bagging/getTeamBags`,
      POST_EXPIRY_DATE: '/api/allocate-stationery/change-expiry',
      CHANGE_ORG_TREE: '/api/team/orgTree/change',
      GET_TEAM_TREE: '/api/team/get/teamTree',
      GET_OPERATION_REPORTS: `/api/analytics/operation-reports`,
      FURTHER_ALLOCATE_STATIONERY: `/api/allocate-stationery/${params[0]}/further-allocate`,
      GET_TICKETS: `/api/ticket`,
      RAISE_TICKET: `/api/ticket`,
      SEARCH_TICKET: `/api/ticket/searchTicket/${params[0]}`,
      GET_TICKET_THREAD: `/api/ticket/getThread/${params[0]}`,
      POST_TICKET_COMMENT: `/api/ticket/comment/${params[0]}`,
      TOGGLE_TICKET: `/api/ticket/toggleTicket/${params[0]}`,
      CHECK_CAN_CREATE_AWB: `/api/book-parcel/checkCanCreateAWB/${params[0]}`,
      CREATE_AUTO_BOOKING: `/api/book-parcel/create-auto-booking`,
      SEARCH_POST_AWB: `/api/book-parcel/searchAWB`,
      IMPORT_BOOKINGS: '/api/book-parcel/import-bookings',
      DOWNLOAD_BOOKING_DATA: '/api/book-parcel/download-booking-data',
      CUSTOMERS: '/api/team/org/customers',
      GET_BOOKING_DETAILS: '/api/book-parcel/get-booking-details',
      SYNC_WITH_SERVER: '/api/book-parcel/sync-with-server',
      FETCH_NEXT_AWB: '/api/book-parcel/next-awb',
      SEARCH_GEO_MASTER_LIST: '/api/geo/level/master/list',
      ORG_BOOKING_COUNT: '/api/analytics/booking-count',
      ORG_SCANNING_COUNT: '/api/analytics/get-scanning-count',
      GET_INVOICE: '/api/pricing/get-invoice',
      GET_INVOICE_TOTAL_AMOUNT: '/api/pricing/get-total-invoice-amount',
      GET_ALLOCATED_AWB_DETAILS: '/api/book-parcel/getAWBStationeryDetails',
      GET_ATTENDANCE_REPORTS: '/api/analytics/get-attendance-report',
      CHARGE_BREAKUP: `/api/team/${params[0]||''}/chargeBreakup`,
      GET_PRODUCT_LEVEL_SETTINGS: `/api/team/${params[0]||''}/productLevelSettings`,
      GET_NOTIFICATIONS: '/api/user/notifications',
      POST_DOWNLOAD_INVOICE_EXCEL: '/api/pricing/download-invoice-excel',
      GET_GEO_GROUP_LIST: '/api/geo/level/group/list',
      GET_GEO_SEARCH_LOCATIONS: `/api/geo/fleetyx/location/search/${params[0]}`,
      POST_DOWNLOAD_DP_REPORT: '/api/book-parcel/download-direct-party-booking-report',
      DOWNLOAD_OPERATION_REPORTS: `/api/analytics/download-operation-reports`,
      SEARCH_MOV_ORDERS: `/api/movOrder/find/${params[0]}`,
      TEAM_DETAIL_CSV: `/api/team/teamDetails/csv`,
      DOWNLOAD_BILLING_REPORT: `/api/analytics/download-billing-reports`,
      CORRECT_AWB_CSV: `/api/pricing/correct-awb-csv`,
      LEVELS_LIST: '/api/geo/level/type/list',
      TOGGLE_CHARGE_BREAKUP: `/api/team/${params[0]||''}/chargeBreakup/toggle`,
      GENERATE_INVOICE: `/api/analytics/generate-invoice`,
      GET_PRICE_GROUP: `/api/pricing/get/${params[0] || ''}`,
      CLONE_RATE: `/api/pricing/group-pricing/clone-high-level`,
      GET_IRREGULAR_LIST: `/api/movOrder/get-irr-parcels`,
      BILLING: `/api/analytics/billing/${params[0]||''}`,
      GET_ORG_DETAILS: `/api/team/get-org-details`,
      GET_TEAM_DETAILS: `/api/team/get-team-details`,
      GET_DELIVERY_PARTNERS_PLUGINS: '/api/delivery-partners/get-plugins',
      DELIVERY_PARTNERS: `/api/delivery-partners`,
      GET_VEHICLE_DETAILS: `/api/book-parcel/getVehicleDetails/${params[0]||''}`,
      GET_REASONS: `/api/team/get/getReasons`,
    };

    if(key && typeof urlBank[key] != 'undefined'){
      return base_url+urlBank[key];
    }else{
      throw new Error('Url is absent from url bank.');
    }
  }catch (err){
    // console.log(err);
  }

};

export default getURL;
